# @format

version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nextjs_bun_drizzle_db
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
